spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/mydb?serverTimezone=UTC}
    username: ${JDBC_DATABASE_USERNAME:root}
    password: ${JDBC_DATABASE_PASSWORD:}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd'T'HH:mm:ss
      time: HH:mm:ss
      
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR
    codes:
      VacanteNempresaUnique: VACANTE_NEMPRESA_UNIQUE
      UsuarioCorreoUnique: USUARIO_CORREO_UNIQUE
      UsuarioTelefonoUnique: USUARIO_TELEFONO_UNIQUE
      CandidatoIdentificacionUnique: CANDIDATO_IDENTIFICACION_UNIQUE
      CandidatoIdUsuarioUnique: CANDIDATO_ID_USUARIO_UNIQUE
      EmpresaNitUnique: EMPRESA_NIT_UNIQUE
      EmpresaIdUsuarioUnique: EMPRESA_ID_USUARIO_UNIQUE
